### ISSUE TITLE
Why sup_iter is not repeated when uda_mode is "False"?

### ISSUE THREAD

**Issue by Liu-Jingyao** [SanghunYun/UDA_pytorch#18]
I observed that when the script loaded the **non-uda.json** configuration file, the training only performed three steps instead of the total_steps number. So I looked at the source code and found that the author explained that **sup_iter is non-repetitive when using non-UDA mode**, which means that training will only use a very small amount of data in data/imdb_sup_train.txt. 
**I would like to know why this setting was adopted？** Thanks.
![image](https://user-images.githubusercontent.com/53286995/144057093-009e88cd-958d-41af-9a3e-5316d01ece10.png)
Relevant code:
train.py

<img src="https://user-images.githubusercontent.com/53286995/144055726-a9f3f732-fbd4-472c-aa35-2310b078237c.png" width="50%" height="50%">

<img src="https://user-images.githubusercontent.com/53286995/144056028-c80d6984-a52c-4504-b126-d208ddf9fef2.png" width="50%" height="50%">

main.py

<img src="https://user-images.githubusercontent.com/53286995/144055893-4cb724fd-60f6-4b7d-94a4-8a0c3912a21e.png" width="60%" height="60%">

**Comment by Hayoung93** [comment]
I didn't fully understand this repo's code nor your question, but maybe this information could help:

Under a situation that unlabeled data is larger than labeled one, UDA iterates labeled data repeatedly so unlabeld data could be seen at least once per epoch. On the other hand, fully supervised training can only work on labeled data, so there's no reason to repeat it.
