### ISSUE TITLE
could you provide the example of raw text file format for train, test, unsup?

### ISSUE THREAD

**Issue by huangjinsuzhou** [SanghunYun/UDA_pytorch#2]
It is not clear to me.  The processed data format is quite clear. Thanks

**Comment by SanghunYun** [comment]
I'm sorry, but I don't have the whole raw file now. So you need to refer UDA officials page and get raw file.

**Comment by huangjinsuzhou** [comment]
Oh, I need to clarify my request.  Indeed there is no raw file in their official page either.

Does your data follow the format such as 
label  '\t'   text  for labeled instance and  text column only for unlabel case? 

Thanks

**Comment by SanghunYun** [comment]
In the past, when I was working on this project, I used to debug the data processing process of the official page to know the raw file. It will be cumbersome to do it yourself. Sorry for not giving you right now.

I didn't fully understand the question...
Did you ask delimiter '\t' in the tsv file?
If it's right. Both labeled and unlabeled files are tsv files with columns separated by '\t'.

**Comment by huangjinsuzhou** [comment]
Yes, my question is, whether the following guess is true.
for the labeled case,  there are 2 columns, label and text, separated by tab.  For un-labeled case, only text column exists?

**Comment by SanghunYun** [comment]
Yes, you're right.

If you want to learn with raw files that are not preprocessed,
labeled data(sup) requires (label, text) and unlabeled data(unsup) requires (original_text, augmented_text). Unlabeled data(unsup) does not require a label

**Comment by huangjinsuzhou** [comment]
Thanks and I will try to apply to my case.
