### ISSUE TITLE
what are the "start" and "end" parameters used when calculating the TSA?

### ISSUE THREAD

**Issue by shamanez** [SanghunYun/UDA_pytorch#5]
I am referring to this [line](https://github.com/SanghunYun/UDA_pytorch/blob/1bf65ec253b286976205d646b03efd54dfd6dd10/main.py#L87)

**Comment by SanghunYun** [comment]
https://arxiv.org/pdf/1904.12848.pdf

![image](https://user-images.githubusercontent.com/45596437/73423419-6c8f8f80-436f-11ea-8e1a-5b03f1c039b2.png)

So,  ηt starts at 1/number of categories and end at 1
(ex. The number of categories is 2 when positive or negative.)

Thank you!

**Comment by shamanez** [comment]
Thanks
